### ISSUE TITLE
Ubuntu "not supported on your current browser"

### ISSUE THREAD

**Issue by parasit** [robyf/google-chat-linux#4] opened 2018-06-08 11:59 UTC
Hey,
When i try start electron in ubuntu got window with information:
"Whoops, sorry, Hangouts Chat is not supported on your current browser.
List of supported browsers"

P.S. Binary release does not exist (error 404).

**Comment by parasit** [comment] 2018-06-10 09:43
I just clone repo, after clone just run `electron .` inside repo folder. 

Link to "releases" (https://github.com/robyf/google-chat-linux/blob/master/robyf/google-chat-linux/releases) from main repo page  returns Http 404.

**Comment by robyf** [comment] 2018-06-10 17:18
I've fixed the link in the readme, thanks. Anyway the same link is available in the top bar of the "Code" section (the one listing commits, branches, etc).

Running locally you might have gotten a different version of electron that sends a different user agent, hard to tell. I'm closing this as I cannot reproduce it.

**Closed by robyf** 2018-06-10 17:18 UTC
